### ISSUE TITLE
fdk-go does not pass protocol info into context of handler function

### ISSUE THREAD

**Issue by sothawo** [fnproject/fdk-go#19]
in order to be able to find the http method which was used to invocate a function of format json, the context passed into a handler method in fdk-go should contain the _protocol_ part of the JSON payload (https://github.com/fnproject/fn/blob/master/docs/developers/function-format.md).

Using the following code  for a json-format function shows that this information is not passed into the handler:

	func main() {
		fdk.Handle(fdk.HandlerFunc(testHandler))
	}
	
	func testHandler(ctx context.Context, in io.Reader, out io.Writer) {
		fnctx := fdk.Context(ctx)
	
		log.Println(fmt.Sprintf("%v", ctx))
		log.Println(fmt.Sprintf("%v", fnctx.Config))
		log.Println(fmt.Sprintf("%v", fnctx.Header))
	
	}

**Comment by rdallman** [comment]
Thanks @sothawo - considering how to rejig our context to expose this better, i'm not sure if we want top level fields for every json field, there's a mismatch now between http and json where if we have top level fields for json we have to yank these out of http headers and put them in there (maybe this is the right thing to do). open to ideas here

**Comment by postak** [comment]
we need at least **REQUEST_URL** as in fdk-node (ctx.protocol.payload.request_url) in order to support GET with query_string parameters

**Comment by denismakogon** [comment]
Yeah, faced with the same need. All other FDKs provide an access to request URL, so we need to set that as well.
The justification is simple - i want to get the Fn API URL to call another function from the current one.

**Comment by sothawo** [comment]
my use case: be able to detect an OPTION request as a CORS preflight

**Comment by denismakogon** [comment]
@sothawo @postak PR created, please review and try it out. Thanks.

**Comment by sothawo** [comment]
sorry for the late answer, it works - I have my method info and can create a correct cors preflight answer 👍

**Comment by denismakogon** [comment]
Good to know. Awesome!
