### ISSUE TITLE
FDK context should expose similar attributes as any other FDK does

### ISSUE THREAD

**Issue by denismakogon** [fnproject/fdk-go#25]
FDK-python context: https://github.com/fnproject/fdk-python/blob/master/fdk/context.py#L51
FDK-ruby context: https://github.com/fnproject/fdk-ruby/blob/master/lib/fdk/context.rb#L10

What else?

**Comment by rdallman** [comment]
kinda would like to get rid of them altogether https://github.com/fnproject/fn/pull/961#pullrequestreview-116065409

**Comment by rdallman** [comment]
done
