### ISSUE TITLE
Add Developer Content to the fdk-go Repo

### ISSUE THREAD

**Issue by michael-w-williams** [fnproject/fdk-go#48]
This repo should have some developer information including:

* How to obtain the Go FDK. 
* How to include the Go FDK in the build for runtime Go images. 
* How to  include the Go FDK in program dependencies when building a custom runtime image using a Dockerfile.

**Comment by rdallman** [comment]
@michael-w-williams I've addressed point 3 (custom runtime image...) here https://github.com/fnproject/fdk-go/pull/51 with a note about it. I added back point 1 as well. wrt 2, i'm really unclear on what to do here, it seems this is already covered https://github.com/fnproject/tutorials/tree/master/Introduction and I've added a link to it in the readme here, which addresses 2 I think. As noted, 3) may be moved elsewhere, but it's not clear to me where this is. feel free to direct me or move it or copy it, but I've updated it and it works to address that specific point now so it should be easy to move around and update the readme there to fit any template it needs to.
